#name: Desktop Release
#
#on:
#  push:
#    branches:
#      - main
#    tags:
#      - 'v*.*.*'
#
#jobs:
#  build-release-desktop:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: set up JDK 17
#        uses: actions/setup-java@v4
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#          cache: gradle
#
#      - name: Grant execute permission for gradlew
#        run: chmod +x ./gradlew
#
#      - name : Build Release Package
#        run: ./gradlew :composeApp:packageReleaseExe :composeApp:PackageReleaseMsi
#
#      - name: Upload Binaries
#        run : actions/upload-artifact@v4
#        with:
#          name : binaries
#          if-no-files-found : error
#          path : 'composeApp/build/compose/binaries/main-release/*'
